### ISSUE TITLE
'intents' Argument Issue

### ISSUE THREAD

**Issue by Photon-Resonance** [hirusha-adi/Discord-Account-Always-Onlie#3]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    client = commands.Bot(">>", self_bot=True)
TypeError: __init__() missing 1 required keyword-only argument: 'intents'

**Comment by hirusha-adi** [comment]
hello, its because of version incompatibility of python discord API. ill fix it

**Comment by hirusha-adi** [comment]
hello, 
everything has been fixed in these commits:

https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/42710b536fe2e3924423c088cc89568d24cc163b
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/1bf3d836cfe2d7a1b46d0a0b59ece46128e5cc18
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/05d6b9e1ed1089553ac7c157165b0fe3e01fb18b
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/db2b158d01f6425cbcd1d3664afaeeb940efe052
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/73a8cfd979977d8ace0f1f1a0a720ae5725cc8ef
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/eb0ed2dde27cadc3ed3745138c84e7bda90e4eb5
https://github.com/hirusha-adi/Discord-Account-Always-Onlie/commit/5c362a6e1fe545d4b99a712650e0b9966127df09

Thank you!
have a nice day and enjoy the tool!
